FROM robinlab/robot-libs-ros-cuda:18.04

RUN pip3 install torch==1.12.0+cu116 \
    torchvision==0.13.0+cu116 \
    torchaudio==0.12.0+cu116 \
    --extra-index-url https://download.pytorch.org/whl/cu116

RUN cd /usr/bin && rm python3 && ln -s python3.7 python3

